insert into image (id, titre, fichier, created_at, updated_at) values (1, 'lorem integer tincidunt ante vel ipsum praesent', 'image.jpg', '2023-05-20 11:05:07', null);
insert into image (id, titre, fichier, created_at, updated_at) values (2, 'eu sapien cursus vestibulum proin eu mi nulla ac enim', 'image.jpg', '2023-10-25 10:52:51', null);
insert into image (id, titre, fichier, created_at, updated_at) values (3, 'eu orci mauris lacinia sapien quis libero', 'image.jpg', '2023-07-20 11:01:06', null);
insert into image (id, titre, fichier, created_at, updated_at) values (4, 'sapien cursus vestibulum proin eu', 'image.jpg', '2023-06-08 16:46:19', null);
insert into image (id, titre, fichier, created_at, updated_at) values (5, 'vehicula condimentum curabitur in libero ut', 'image.jpg', '2023-04-13 15:11:10', null);
insert into image (id, titre, fichier, created_at, updated_at) values (6, 'enim lorem ipsum dolor sit amet consectetuer', 'image.jpg', '2023-09-16 16:36:28', null);
insert into image (id, titre, fichier, created_at, updated_at) values (7, 'lorem vitae mattis nibh ligula nec sem duis', 'image.jpg', '2023-12-25 04:22:11', null);
insert into image (id, titre, fichier, created_at, updated_at) values (8, 'aliquam lacus morbi', 'image.jpg', '2023-05-27 18:57:40', null);
insert into image (id, titre, fichier, created_at, updated_at) values (9, 'vestibulum ante ipsum primis in faucibus orci luctus', 'image.jpg', '2023-10-11 03:02:07', null);
insert into image (id, titre, fichier, created_at, updated_at) values (10, 'dictumst maecenas ut massa quis augue luctus tincidunt', 'image.jpg', '2023-06-16 00:09:02', null);
insert into image (id, titre, fichier, created_at, updated_at) values (11, 'feugiat non pretium quis lectus suspendisse potenti', 'image.jpg', '2023-03-26 17:50:20', null);
insert into image (id, titre, fichier, created_at, updated_at) values (12, 'quis turpis sed ante vivamus tortor duis mattis', 'image.jpg', '2023-05-24 14:56:46', null);
insert into image (id, titre, fichier, created_at, updated_at) values (13, 'nec nisi volutpat eleifend donec ut dolor morbi vel', 'image.jpg', '2023-02-22 11:04:34', null);
insert into image (id, titre, fichier, created_at, updated_at) values (14, 'adipiscing elit proin interdum mauris', 'image.jpg', '2023-04-06 00:48:07', null);
insert into image (id, titre, fichier, created_at, updated_at) values (15, 'congue elementum in hac habitasse', 'image.jpg', '2023-12-01 07:50:06', null);
insert into image (id, titre, fichier, created_at, updated_at) values (16, 'auctor gravida sem praesent', 'image.jpg', '2023-07-31 00:07:42', null);
insert into image (id, titre, fichier, created_at, updated_at) values (17, 'lectus in est risus auctor sed tristique in tempus sit', 'image.jpg', '2023-10-13 21:25:41', null);
insert into image (id, titre, fichier, created_at, updated_at) values (18, 'at velit eu est congue elementum in hac', 'image.jpg', '2023-09-01 04:47:53', null);
insert into image (id, titre, fichier, created_at, updated_at) values (19, 'mauris viverra diam vitae quam suspendisse potenti nullam', 'image.jpg', '2023-04-22 09:18:49', null);
insert into image (id, titre, fichier, created_at, updated_at) values (20, 'eget massa tempor convallis nulla neque libero', 'image.jpg', '2023-12-15 19:21:51', null);
